name: Upload Region Files to S3 and SharePoint

on:
  push:
    branches:
      - main
    paths:
      - 'maps-topic-qa/Topics/Region/**'

jobs:
  upload-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
 
      - name: Upload Region Files to S3 with Prefixed Filenames
        run: |
          for file in $(find maps-topic-qa/Topics/Region -type f); do
            country=$(echo "$file" | cut -d'/' -f4)
            filename=$(basename "$file")
            aws s3 cp "$file" "s3://oxygen.xml/maps-topic-qa/Topics/Region/$country/${filename}"
          done

      - name: Upload Files to SharePoint
        run: |
          CLIENT_ID="${{ secrets.CLIENT_ID }}"
          CLIENT_SECRET="${{ secrets.CLIENT_SECRET }}"
          DRIVE_ID="${{ secrets.DRIVE_ID }}"
          SITE_ID="${{ secrets.SITE_ID }}"
          FILE_PATH="maps-topic-qa/Topics/Region/yourfile.dita"

          # Get OAuth2 Access Token
          TOKEN_RESPONSE=$(curl -X POST \
            -d "grant_type=client_credentials&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&scope=https://graph.microsoft.com/.default" \
            "https://login.microsoftonline.com/common/oauth2/v2.0/token")

          ACCESS_TOKEN=$(echo $TOKEN_RESPONSE | jq -r .access_token)

          # Upload File to SharePoint
          curl -X PUT \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: text/plain" \
            --data-binary "@$FILE_PATH" \
            "https://graph.microsoft.com/v1.0/sites/$SITE_ID/drives/$DRIVE_ID/root:/Europa/$FILE_PATH:/content"
