name: Upload Region Files to S3

on:
  push:
    branches:
      - main
    paths:
      - 'topic/region/**'

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Update to your desired AWS region

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: List files in topic/region directory
        run: ls -R topic/region/

      - name: Upload Region Files to S3 with Prefixed Filenames
        run: |
          for file in $(find topic/region -type f); do
            filename=$(basename "$file")
            aws s3 cp "$file" "s3://oxygen.xml/region_${filename}"
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1  # Update to your desired AWS region
